### ISSUE TITLE
Nice job, Is there a plan to release the code?

### ISSUE THREAD

**Issue by jucic** [megvii-research/CREStereo#1]

**Comment by MartinPeris** [comment]
+1, I have been reading the paper. Great job! Code and/or trained models to reproduce the results would be greatly appreciated.

**Comment by ppyht2** [comment]
+1, really great work guys, but I'm super curious on how the adaptive local correlation is implemented. The cost volume approach has been suboptimal for deep learning, so It's exciting to see improvements promising better results than the RAFT correlation approach.

**Comment by JackLee396** [comment]
Thank you for your interest. Code and pre-trained models will be released in a few days :)
