### ISSUE TITLE
Did you obtain results on Holopix50k with published model?

### ISSUE THREAD

**Issue by shkarupa-alex** [megvii-research/CREStereo#15]
I've tried to run published model with few images from Holopix50k and got awful results.
Can you please tell how to obtain results similar to paper? Another model / another preprocessing?

**Comment by JackLee396** [comment]
We performed a rectification step on this dataset before stereo matching https://github.com/megvii-research/CREStereo/issues/9#issuecomment-1131230448

**Comment by Tord-Zhang** [comment]
@JackLee396 Could you please share how to do the rectification without camera intrinsics?

**Comment by Tord-Zhang** [comment]
@shkarupa-alex
