### ISSUE TITLE
TypeError: pad() got an unexpected keyword argument 'pad_witdth' in test.py

### ISSUE THREAD

**Issue by city19992** [megvii-research/CREStereo#34]
Good job! May I ask a question?

I tried to run the test.py on a V100 with the Cuda version being 10.2. The data is from ./img, and I set the size being 1280*720, the same as the original size. But I meet the following error:

`File "CREStereo/nets/corr.py", line 42, in get_correlation
    (0, 0), (0, 0), (pady, pady), (padx, padx)), mode="replicate")
TypeError: pad() got an unexpected keyword argument 'pad_witdth'`

It means that I may use the wrong type, but I checked the code and did not find the problems:
`

def pad(
    src: Tensor,
    pad_width: Tuple[Tuple[int, int], ...],
    mode: str = "constant",
    constant_value: float = 0.0,
) -> Tensor:
    r"""Pads the input tensor.

    Args:
        pad_width: A tuple. Each element in the tuple is the tuple of 2-elements,
            the 2 elements represent the padding size on both sides of the current dimension, ``(front_offset, back_offset)``
        mode: One of the following string values. Default: ``'constant'``

            * ``'constant'``: Pads with a constant value.
            * ``'reflect'``: Pads with the reflection of the tensor mirrored on the first and last values of the tensor along each axis.
            * ``'replicate'``: Pads with the edge values of tensor.
        constant_val: Fill value for ``'constant'`` padding. Default: 0

    Examples:
        >>> import numpy as np
        >>> inp = Tensor([[1., 2., 3.],[4., 5., 6.]])
        >>> inp
        Tensor([[1. 2. 3.]
         [4. 5. 6.]], device=xpux:0)
        >>> F.nn.pad(inp, pad_width=((1, 1),), mode="constant")
`

I used the right Tuple type, but something wrong happened.

**Comment by yupeichen** [comment]
In the original corr.py line 39 (line 42 in your case), change 'pad_witdth' to 'pad_width' should solve the problem. Hope this helps!

**Comment by city19992** [comment]
> In the original corr.py line 39 (line 42 in your case), change 'pad_witdth' to 'pad_width' should solve the problem. Hope this helps!

@yupeichen Thank you! I take many things into consideration except this. It works.
