### ISSUE TITLE
What datasets are used for pretraining?

### ISSUE THREAD

**Issue by DY-ATL** [megvii-research/CREStereo#5]
The pretrained model works amazingly well on the real-life photos! What datasets are used for pretraining?
Can you please provide the training details of the pretrained model? Thanks!

**Comment by JackLee396** [comment]
As described in Sec 4.1 in the paper, in addition to our rendered dataset, we collect major public datasets for training including Sceneflow, Falling Things, Airsim, etc. No pre-training steps are implemented.

**Comment by ynma-hanvo** [comment]
> As described in Sec 4.1 in the paper, in addition to our rendered dataset, we collect major public datasets for training including Sceneflow, Falling Things, Airsim, etc. No pre-training steps are implemented.

hi,  how did you convert the sceneflow dataset into crestereo format,  as i checked its content, there is only flow data which looks different from disparity.

**Comment by hgchen** [comment]
A quick question about the provided pre-trained model "crestereo_eth3d.mge". We wonder what dataset that particular model was trained on. According to your paper section 4: "In addition to our rendered dataset, we collect major public datasets for training, including Sceneflow [27], Sintel [5] and Falling Things [46]." We wonder if you trained that model on all the synthetic datasets, and then fine-tuned it with the ETH3D datasets? 

If that's the case, you mentioned "We train our network on the whole training set with a proportion of 2% augmented training data from ETH3D low-res two-view stereo dataset." in your paper, did you use only the very small "low-res two-view" subset, or did you use the "high-res multi-view" and "low-res multi-view" subsets as well?

Thanks a lot for your answers, really appreciate your time!
