### ISSUE TITLE
test.py hangs up when model is initializing

### ISSUE THREAD

**Issue by jucic** [megvii-research/CREStereo#6]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/17615552/161228394-2013eef9-799f-47bb-a72d-774f4fb100d8.png">

please see the picture above, code hangs up on line 16

**Comment by luhu65** [comment]
我最近也在跑这个代码 可以和您交流一下吗？

**Comment by zhanghongruiupup** [comment]
> <img alt="image" width="1102" src="https://user-images.githubusercontent.com/17615552/161228394-2013eef9-799f-47bb-a72d-774f4fb100d8.png">
> 
> please see the picture above, code hangs up on line 16

The same problem, the code does not work

**Comment by luhu65** [comment]
I have successfully run the code on the Linux system, but failed on the windows system. The reason for the failure is the same as you. It is recommended to reconfigure the environment on the Linux system. Good luck!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月2日(星期六) 下午5:58
收件人: ***@***.***&gt;; 
抄送: "Erwin Schrodinger’s ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [megvii-research/CREStereo] test.py hangs up when model is initializing (Issue #6)





   
please see the picture above, code hangs up on line 16
  
The same problem, the code does not work

**Comment by jucic** [comment]
I failed with cuda 11.3 and then succeded with cuda 10.2

**Comment by LaiHei** [comment]
凯哥威武

**Comment by jucic** [comment]
> 凯哥威武

你是？手动捂脸
