### ISSUE TITLE
Results on Holopix50k dataset

### ISSUE THREAD

**Issue by coffeehanjan** [megvii-research/CREStereo#9]
Hello! Thank you for sharing the codes and the model. 
I tested the pre-trained model on Holopix50k test dataset, but didn't get similar results that you showed on the paper. 
If I would like to run crestereo_eth3d.mge model on this dataset, does it require different parameter setting or pre-preprocessing? How I can get the similar results on Holopix50k dataset?
Any advice would be very helpful. Thank you in advance! 
![0001](https://user-images.githubusercontent.com/103703532/163495725-02250384-724e-4e49-ad0c-85b72f3cd3f1.png)
![0002](https://user-images.githubusercontent.com/103703532/163495729-a63fcb61-803a-46a2-a1ef-98f689930543.png)
![0007](https://user-images.githubusercontent.com/103703532/163495732-eee8322e-0555-49af-a170-5155058d6458.png)
![0008](https://user-images.githubusercontent.com/103703532/163495733-9dd04700-9264-4656-b175-870d884cbf50.png)

**Comment by JackLee396** [comment]
We perform pre-rectification on this dataset to eliminate negative disparity or imbalanced scales because the original pairs are not rectified.

**Comment by AppleAndBanana** [comment]
> We perform pre-rectification on this dataset to eliminate negative disparity or imbalanced scales because the original pairs are not rectified.

Can you please give me some advices about how to perform the pre-rectification? Method or code are both ok.

**Comment by Tord-Zhang** [comment]
@JackLee396 Hi, could you please show the code for pre-rectification? Thanks

**Comment by Tord-Zhang** [comment]
@AppleAndBanana Hi, any suggestions on rectification?

**Comment by ptoupas** [comment]
Hi, @AppleAndBanana, @Tord-Zhang,

Have you managed to find what is the pre-rectification used for the Holopix50k dataset after all?

@JackLee396 do you maybe have published that code or mentioned the method used anywhere?
